# Generated by Django 3.1 on 2020-08-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
